imports:
        - { resource: parameters.yml}

services:
#    nfq_weather.example:
#        class: Nfq\WeatherBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
     nfq_weather.parser.openweathermap:
         class: Nfq\WeatherBundle\Parsers\OpenWeatherMapDataParser
         public: false

     nfq_weather.provider.openweathermap:
          class: Nfq\WeatherBundle\Providers\OpenWeatherMapProvider
          arguments: ["@nfq_weather.parser.openweathermap","%openweathermap_api_key%"]

     nfq_weather.parser.yahoo:
          class: Nfq\WeatherBundle\Parsers\YahooWeatherDataParser
          public: false

     nfq_weather.provider.yahoo:
          class: Nfq\WeatherBundle\Providers\YahooWeatherProvider
          arguments: ["@nfq_weather.parser.yahoo"]

     nfq_weather.provider.delegating:
           class: Nfq\WeatherBundle\Providers\DelegatingProvider
           arguments: ["%nfq_weather.providers%"]

     nfq_weather.provider.cached:
           class: Nfq\WeatherBundle\Providers\CachedProvider
           arguments: ["%nfq_weather.cached_provider%","%ttl%"]


